sonar.projectKey=renewable-asset-system
sonar.projectName=Renewable Asset System
sonar.sources=src,assets-ui/src
sonar.tests=tests,assets-ui/src/__tests__
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/build/**
sonar.cs.opencover.reportsPaths=coverage/backend/coverage.opencover.xml
sonar.javascript.lcov.reportPaths=assets-ui/coverage/lcov.info
sonar.sourceEncoding=UTF-8
